# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-phela-http-to-https
spec:
  parentRefs:
    # Must attach to your HTTP listener on the Gateway
    - name: internal
      sectionName: http-phela
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            port: 443
            statusCode: 301 # optional; default is 302
