# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: "192.168.69.7"
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "internal.${SECRET_DOMAIN}"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.${SECRET_DOMAIN}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: ${SECRET_DOMAIN/./-}-production-tls
    - name: https-phela
      protocol: HTTPS
      port: 443
      hostname: "phela-intelligence.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: phela-staging-tls
    # - name: http-phela-wildcard
    #   protocol: HTTP
    #   port: 80
    #   hostname: "*.phela-intelligence.com"
    #   allowedRoutes:
    #     namespaces:
    #       from: Same
    # - name: https-phela-wildcard
    #   protocol: HTTPS
    #   port: 443
    #   hostname: "*.phela-intelligence.com"
    #   allowedRoutes:
    #     namespaces:
    #       from: All
    #   tls:
    #     certificateRefs:
    #       - kind: Secret
    #         name: phela-staging-tls
