# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/networkpolicy.json
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ns-ingress
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-only-reserved-ingress
spec:
  description: "Allow ingress only from Cilium reserved:ingress identity"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/controller: home-assistant
      app.kubernetes.io/instance: home-assistant
      app.kubernetes.io/name: home-assistant
  ingress:
    - fromEndpoints:
        # match the special reserved identity for ingress traffic
        - matchExpressions:
            - key: reserved:ingress
              operator: Exists
