# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: home-assistant
spec:
  description: "Network policies for home-assistant"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "8123"
  egress:
    - toCIDR:
        - "192.168.68.0/23"
    - toServices:
        - k8sService:
            namespace: home-assistant
            serviceName: mosquitto
      toPorts:
        - ports:
            - port: "1883"
              protocol: TCP
    - toFQDNs:
        - matchPattern: "*.api.met.no"
        - matchName: www.googleapis.com
        - matchName: data-v2.hacs.xyz
        - matchName: alerts.home-assistant.io
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
