# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: home-assistant
spec:
  description: "Network policies for home-assistant"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "8123"
  egress:
    - toCIDR:
        - "192.168.68.0/23"
    # - toServices:
    #     - k8sService:
    #         namespace: home-assistant
    #         serviceName: mosquitto
    - toCIDR:
        - "224.0.0.251/32" # IPv4 multicast discovery
      toPorts:
        - ports:
            - port: "5353"

    - toCIDR:
        - "239.255.255.250/32" # SSDP/UPnP multicast discovery
      toPorts:
        - ports:
            - port: "1900"
    - toCIDR:
        - "255.255.255.255/32" # UDP broadcast for SSDP/UPnP discovery
      toPorts:
        - ports:
            - port: "1900"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: home-assistant
            k8s:app.kubernetes.io/name: mosquitto
      toPorts:
        - ports:
            - port: "1883"
              protocol: TCP
    - toFQDNs:
        - matchPattern: "*.api.met.no.svc.cluster.local"
        - matchPattern: "*.googleapis.com.svc.cluster.local"
        - matchName: data-v2.hacs.xyz.svc.cluster.local
        - matchName: alerts.home-assistant.io.svc.cluster.local
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
