# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/networkpolicy.json
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zigbee-egress
spec:
  podSelector:
    matchLabels:
      name: zigbee2mqtt
  policyTypes:
    - egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: home-assistant
          podSelector:
            matchLabels:
              instance: mosquitto
      ports:
        - port: 1883
          protocol: TCP
