# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-credentials
stringData:
  user: ENC[AES256_GCM,data:H/NGkgHX,iv:blVBlznmUGcBecL/dFn+EoErMiIA0buFK4btldTtqZU=,tag:3PTZkRKFZ/MgLJ9dJJYdhQ==,type:str]
  password: ENC[AES256_GCM,data:jI86rzcbThQEarb2h5J76odhhf6YQEbxe/1MKy8RGJxLxDCuJb4tUxBwcdyuMg==,iv:GUg9F7f2w2sM4H0MTjsZ3orTdBBBx/YRHwrKdPFZUjQ=,tag:wS1V7TN2xKHgK+SW91d2Jw==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcVY1MjIyTWlCbGJxcitD
        d1FQRjBpb3owOERmbDZxbG9Zc1NmdXd3RjBVCktxMzRhNVhmL0kyclNCM0RNeVZs
        THBobTMvQURPMFE3dUhvYkRSWjVaK0kKLS0tIGlIMGpoaUhHenBHYkVJWlVVUUVm
        NDFhS05ZVU52Y1ZnQWduaGtzWS9vaUEK2htDaWocq+RzMjXIGuLnL+H6cjBdz22M
        N2raR4GuizsaaYRj4xue/BtekeRib3WywJeXFgUet7uK6QOSiJt+dQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:23:54Z"
  mac: ENC[AES256_GCM,data:u2ebtvGAGmbfJ6dPxUXZJZAUJzpiVplGahsQbAfXRo5xdFt1T4I2QgNkbooxV0n+05CONK8D4oO4yt5+N1cqYzc5Rgg39cq4XgWIngni3uaH+0vpiZ7nRvWlLI/kGDLrSaBVZLoWSZFmwLMUPBWyvuQAIJ7nHxA7bZcBZt7kxZM=,iv:F4KhCOBZIuWY/YxUa8AM6sWnp8QXqQN/Rep/XDEnL+A=,tag:sO4qOr068AmzaFh+lJsBZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
