# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-credentials
stringData:
  user: ENC[AES256_GCM,data:H/NGkgHX,iv:blVBlznmUGcBecL/dFn+EoErMiIA0buFK4btldTtqZU=,tag:3PTZkRKFZ/MgLJ9dJJYdhQ==,type:str]
  password: ENC[AES256_GCM,data:jI86rzcbThQEarb2h5J76odhhf6YQEbxe/1MKy8RGJxLxDCuJb4tUxBwcdyuMg==,iv:GUg9F7f2w2sM4H0MTjsZ3orTdBBBx/YRHwrKdPFZUjQ=,tag:wS1V7TN2xKHgK+SW91d2Jw==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcVY1MjIyTWlCbGJxcitD
        d1FQRjBpb3owOERmbDZxbG9Zc1NmdXd3RjBVCktxMzRhNVhmL0kyclNCM0RNeVZs
        THBobTMvQURPMFE3dUhvYkRSWjVaK0kKLS0tIGlIMGpoaUhHenBHYkVJWlVVUUVm
        NDFhS05ZVU52Y1ZnQWduaGtzWS9vaUEK2htDaWocq+RzMjXIGuLnL+H6cjBdz22M
        N2raR4GuizsaaYRj4xue/BtekeRib3WywJeXFgUet7uK6QOSiJt+dQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:40:58Z"
  mac: ENC[AES256_GCM,data:SLH3Z+b+6GR7eGS3YHn+GWqOjRUT+aQWrDTUt5nBt82X5Dhq5BAuwx2zQ5fOf4cOnSynkgcf07Cz3Cz69x5agULYP2HoGCF8pXPESfwBmR3VkDHp64uaHgqfW+A+rjAGRiROUHldd2wciXhESy1YilU+aK10Cf9okqMCzQGCTqU=,iv:RP2S6qJeVC5UJTbRFImXH+zvpdw3KPkJ0M7CI+2kdLE=,tag:eosrj4BdfM5b6estB9Uu9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
