zigbee2mqtt:
  timezone: Europe/Amsterdam
  mqtt:
    server: mqtt://mosquitto.home-assistant.svc.cluster.local:1883
  serial:
    adapter: ember
service:
  type: ClusterIP
statefulset:
  nodeSelector:
    kubernetes.io/hostname: c-00
  storage:
    enabled: true
    storageClassName: ssd-lvm-thin-1
