# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piraeus-datastore
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: piraeus-datastore
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: piraeus-operator
  valuesFrom:
    - kind: ConfigMap
      name: values-piraeus-datastore
    - kind: ConfigMap
      name: values-piraeus-datastore
      valuesKey: env-values.yaml
