# yaml-language-server: $schema=https://json.schemastore.org/kustomization
resources:
  - dashboard.yaml
  - helmrelease.yaml
  - httproute.yaml
  - passphrase.sops.yaml
  - source.yaml
  - storageclass.yaml
  - volumesnapshotclass.yaml
configMapGenerator:
  - name: values-piraeus-datastore
    behavior: create
    files:
      - values.yaml=values.yaml
    literals:
      - env-values.yaml=''
configurations:
  - ../../../utils/helm/kustomizeconfig.yaml
