# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: linstor-passphrase
stringData:
  MASTER_PASSPHRASE: ENC[AES256_GCM,data:q2wCtuzO5UVQYCNS1MwvV3Y5Ebn7YnvR0AoXAgrAy7Um44UZrth3o3X/ucjiL4h2fW4b1SPj5ks=,iv:9Nh6gtji5QdooG09sAWF/3k5QoLFByzEiPUg6Ztf1NM=,tag:XyMDrdxo+rWEiQYUzzK91w==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdDlFdzlmTFhOV2JOZXJE
        dE1UVzA1alNwbG03VC9kU0Q1TVZUUnpOMmpjCng4UVpDMm8rcVFKUFJ4WnVlTStq
        cGQ2SHZrSGtWRlZISzlxZ2JnRFc4QUUKLS0tIEwzRU5GdDY5YVprQ0lNSE40bTF2
        dFFPcHVqeEZ0TnBHRUNZUzBBaEUvd1EKqJ9o7jshi4F2uiWfvUXNYjTQMg66mgKX
        2jleOXX18b2LJAEkOzr7h7RQfVSV5iXENrLsvwiuAj/JMfjUBBuVUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:24:06Z"
  mac: ENC[AES256_GCM,data:nh8TF2YQL9UhNwmhreJy9c5OkbBcz5zfQX6occ9clUwxebHyIQiaCsowHN4Ly921EZfKbu4qingNg6l05b0vXNyfRo1bhqfN93Q1hBrdPc/2hIxflGliBkRAd7vxUpOxEqveVqhYYFeMAcyrfFvzvmjSVRKiNcA3eORUbgg9iBI=,iv:Ao+z524lCniT6ztkZrAwP/+d+jvp2sFIQLKJkADfizE=,tag:mTR4f1M6KgkpK0S9600bmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
