apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters: #https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-kubernetes-sc-parameters
  linstor.csi.linbit.com/storagePool: lvm-thin
  linstor.csi.linbit.com/placementCount: "2"
