apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-lvm-thin-1
  annotations:
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters: #https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-kubernetes-sc-parameters
  linstor.csi.linbit.com/storagePool: ssd-lvm-thin
  linstor.csi.linbit.com/placementCount: "1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-lvm-thin-2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters: #https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-kubernetes-sc-parameters
  linstor.csi.linbit.com/storagePool: ssd-lvm-thin
  linstor.csi.linbit.com/placementCount: "2"
