# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - cluster-netpol.yaml
  - cm-hubble-metrics.yaml
  - grafana-dashboard.yaml
  - helmrelease.yaml
  - source.yaml
  - networks.yaml
configMapGenerator:
  - name: values-cilium
    behavior: create
    files:
      - values.yaml=values.yaml
    literals:
      - env-values.yaml=''
configurations:
  - ../../../utils/helm/kustomizeconfig.yaml
