# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-api-token
stringData:
  api-token: ENC[AES256_GCM,data:5afoLWnk9zWs+G07JGKTOUkR1cWonLMsgTS++wuKI3h8vdivMV15SA==,iv:dnJw00O+PSe7mXFTI5A9DjPUNsQKF3OVq7mj3mx900I=,tag:FHRxfbxFeX3fA2smsxI6sw==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwemVXRFIzWW9oZmZrOWxV
        MUJGRmVRL3k5MzhtUHplOFpuaXFjUkFIdjBRClVWQkRTbVdiRlhYTnhyVmVwd0lM
        eHNBRXF1RnA1UVhiSmppcE9BMnFUbDgKLS0tIDJ1WkFuWm1FekJvNWhSK2gxTWJY
        UUR1Z05OODZVRENJTVNXL3BnYjdrQ1EKaXx/AeVZpb5pAW4SFAgCZvWw0HdwxWAJ
        ynVBzjD3pZ2H+kc++bZyJcIqPqniYexQIFsYEsTwBeBH2ZBI4l/KOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T11:05:02Z"
  mac: ENC[AES256_GCM,data:3TBKexzO9jdwfr9+kNj2E7XCidVglKYI2z3jZDABgCRrBNTfz9dkRWJqalugTQzafS4DiZskW0AMLXbffB1V5Rt4LJxDgUrNHwVKILJ/FbqoCDMeFLBgeCAlKjKQZs7qampZTkQw5eDRxUg7yKXCjlcGXUx3pIGHhS+UbhM8JRg=,iv:PUNPIojKKo42isXSon7TjOIM+6ZERh3hJeR4MhLSeS8=,tag:S/z1Ear6bqTmmUXOCgiBbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
