# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-crds
spec:
  interval: 1h
  path: ./client/config/crd
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-app
spec:
  dependsOn:
    - name: external-snapshotter-crds
  interval: 1h
  path: ./deploy/kubernetes/snapshot-controller
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  timeout: 5m
  wait: false
