# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  access-key: ENC[AES256_GCM,data:AGWMSBCSWplFf6bQpMkOvp2CGzI=,iv:K4n2Fr3RvSrKWpxoXvdNESspxdmczVevobTimsnMs1A=,tag:QKnFOGLiOO/3jsU74rj48A==,type:str]
  secret-key: ENC[AES256_GCM,data:E17lzFFNSyOTtoAM8UHjqpg+kfSOBn5wdCAjRoMZKoBtCEl1RytXAw==,iv:8RHx7UXChzrdKk7nvVNAKg+2PrUXbcyNcDYftg4s1dU=,tag:wo6oYh4hIUdp7OkTbDkBcw==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheUhVYitBbThpMFhqRnJQ
        cUtmZC92TWZXSmNudVQ0QWozOEJERjErWGg4CnhJQkorckE0WjlraVoybjFBTHBz
        R0prOW1XNXQvcXNTOWdhSlMwTk9QWFkKLS0tIC9HQ1hPNm56NGdKVlVLUXprL05B
        TEtTRi93OUE5Q00wbm9reWZrRUYzYUUKbi8m4pJeseLeGBjobJKLnDdpxnAtyVuT
        TWLxHoXKjy+8LztPuTTkb4M2NE3ECqezmEeq+RWc75KEsFZX5JfjwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T16:06:45Z"
  mac: ENC[AES256_GCM,data:4oPQARSIaDUD21NMOhssE6VL09FfzxFn4N8er5aXxyOhXIGf6F0o2D4cyXWlte7GFOq3ejLNh39JxzYsqQPNnD1AzYZbfaruvdAAhGMflPVSkPUKy1NzL0IM0ajRuv5Uw0PczqSY3lI1ruLyFjFIH3vaLD+920lRy74kWidVYtI=,iv:Kwiwc+gMuUxHWMBuLa6s+45rCSkTEvh9ni/0HYHpBaU=,tag:8o2KE9Q/EsYSPKapGthQxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
