apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
spec:
  interval: 1h
  url: https://github.com/kubernetes-csi/external-snapshotter
  ref:
    tag: v8.4.0
