# yaml-language-server: $schema=https://json.schemastore.org/kustomization
resources:
  # - cluster-netpol.yaml
  - grafana-datasource.yaml
  - helmrelease.yaml
  - prometheus-rule.yaml
  - source.yaml
configMapGenerator:
  - name: values-kube-prometheus-stack
    behavior: create
    files:
      - values.yaml=values.yaml
    literals:
      - env-values.yaml=''
configurations:
  - ../../../utils/helm/kustomizeconfig.yaml
