grafana:
  enabled: false
  forceDeployDatasources: true
  forceDeployDashboards: true
  operator:
    dashboardsConfigMapRefEnabled: true
    matchLabels:
      dashboards: grafana
    folder: kube-prometheus-stack
  defaultRules:
    rules:
      kubeProxy: false
  defaultDashboardsTimezone: Europe/Amsterdam
  defaultDashboardsEditable: false
kubeProxy:
  enabled: false
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          # storageClassName: piraeus-storage
          resources:
            requests:
              storage: 5Gi
