# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-cloudlflare
spec:
  description: "Allow egress to cloudflare via DNS-aware FQDN policy"
  endpointSelector:
    matchLabels: {}
  egress:
    - toFQDNs:
        - matchName: region2.v2.argotunnel.com
