apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: phela
spec:
  forProvider: {}
  providerConfigRef:
    name: mysql
---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: User
metadata:
  name: phela
spec:
  forProvider:
    passwordSecretRef:
      name: mysql-credentials
      key: password
      namespace: phela
    resourceOptions:
      maxQueriesPerHour: 50000
      maxUpdatesPerHour: 10000
      maxConnectionsPerHour: 1000
      maxUserConnections: 25
  providerConfigRef:
    name: mysql
