apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: phela
spec:
  forProvider: {}
  providerConfigRef:
    name: mysql
---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: User
metadata:
  name: phela
spec:
  forProvider:
    passwordSecretRef:
      name: mysql-credentials
      key: PASSWORD
      namespace: phela
    resourceOptions:
      maxQueriesPerHour: 50000
      maxUpdatesPerHour: 10000
      maxConnectionsPerHour: 1000
      maxUserConnections: 25
  providerConfigRef:
    name: mysql
---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: phela
spec:
  forProvider:
    privileges:
      - SELECT
      - INSERT
      - UPDATE
      - DELETE
      - CREATE
      - DROP
      - ALTER
      - INDEX
    userRef:
      name: phela
    databaseRef:
      name: phela
  providerConfigRef:
    name: mysql
