# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
stringData:
  PASSWORD: ENC[AES256_GCM,data:3GhjUQ9mtEQLg7vyG+jA++cCM4Q7YcYd0nza+WmMfJcRaXlIgqg4vUZkSNv8ig==,iv:8p5GjyHLPyK5vfRo/kjGdNECP624DGp8x57IWNi99uA=,tag:iheQOD/7nSjxhuJwV0N6dQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYm13SGx2bUNEc3VlN1pm
        Q3VOUzJneUI1NDFwc29lTXhDUzJjdnBUcEdNCkhvK3RwR0tWUTFJdEdmZk13eWUx
        QXNXSUZiSERrTmdaUHZOV0xQREhvY0kKLS0tIG0wckhrUHpQRDhMdXk1eTVkaTY5
        Q0ZHMGJ4MlM5T3RjTm0wTDdjVDluVkkKY+hkFSFpquh/DV9F4lmu6+mKnW7qkwtl
        QpwBvDdX3QZT3bFno4c2ShrO29Ini9DA6Pjxzb5szJAuE6lTQm0BDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T16:30:02Z"
  mac: ENC[AES256_GCM,data:SBOWYOW7bhued963x6i+/Lx4QILOZc0S5ZiSMtkFd2xx6qzgRuiWWLaqrlnfElbvJm2+QRsu2XAGRF5esN18VzGV2Z9jeDVLsGvUdSmVCgJpKkglCQM34iSztrOarIwAL1EDQ8hn37BafFzpQWdxrDp+1koAn69qW7oCn4aGNjY=,iv:IJOyqmPuo+NRTmYizkeqgTWyVKrzaSklRItPExf9zQk=,tag:oEEA4v4bgy2sIJrAE6zoNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
