# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
stringData:
  MYSQL_USER: ENC[AES256_GCM,data:tBXp009vQJHq,iv:piSFkxt/JZEAGHoJcJVDa2FlrX2zcXfxyj+dldLvTLQ=,tag:odCEj8hNjwRUj0WqJTEJLA==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:q+IzPO0bNtEFVWENpN8nzB25QAEMg5gn7T+J6PUIf45fXIOQoMSJRnWmwM+YIg==,iv:0eQ3OJeSl9HU6gvuL8UXJBHP5g7/9OtXXgBAvcb33dU=,tag:1+VIt+1r7hW+Al2+t2wLXA==,type:str]
  MYSQL_DATABASE: ENC[AES256_GCM,data:CTFVSYQq5AE7,iv:rNF3+5bgyeUDZqZ0Sa5dOxBYoPmhdrpnJJBU/YUFOvY=,tag:KtNIM8LUPdwZLbgRsl295w==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobjJyZHJkYmJtUFZLQTJw
        VU91WlZyRW1ZdHMyaGVKOWtJM29POFR5LzFBCksrZnRGbGRjTXIzMkZ1VHN5WnBy
        NzlPaVI0L0V4N2xLOXlOdGdCQzdaY3MKLS0tIHJNeFdRZnJwQzFhOWxaaVBTdTY1
        RDVxek5Jb1NHdGwxTVdVWE5oS2RTblUKMyaa1BBLjSU55b4OMn65dMHeBW8Hgxmx
        yd99eVk8OmEFAb+HUhJ/GQ6650BI1pqG84PMwNkL6oFPYIPCADa9qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T10:27:02Z"
  mac: ENC[AES256_GCM,data:ROuaypd4JwZGiqPOD68mhETHWzceoKHU6CE94Kfyaxf/6yxNRvLzg9XhPjbT3lJTiG1u9TEvLwL8OgNpXjE9KhQVhue27hjogISQrwK85Y8kSegSGIJLmj+FEbRESlzslh15Z5BYS/kK59j9VIgfAzxU8BzwF2g2OHcLaGzZ4R0=,iv:nYgR4DG7ktf56Tb6tr+zsfkB1fbMzOR84q6v38n0i3o=,tag:fBqe9l/h4CjWWQ9dhoYhQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
