# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: phela
spec:
  description: "Allow the ingress traffic from reserved ingress identity"
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: phela
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "80"
  egress:
    # - toEndpoints:
    #     - matchLabels:
    #         k8s:io.kubernetes.pod.namespace: mysql
    #         k8s:app.kubernetes.io/name: mysql-router
    - toServices:
        - k8sService:
            namespace: mysql
            serviceName: mysql
