# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: phela
spec:
  description: "Allow the ingress traffic from reserved ingress identity"
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: phela
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "80"
  egress:
    # - toCIDRSet:
    #     - cidr: "0.0.0.0/0"
    #       except: ["192.168.68.0/23"]
    #   toPorts:
    #     - ports:
    #         - port: "80"
    #           protocol: TCP
    #         - port: "443"
    #           protocol: TCP
    #       rules:
    #         http: [{}]
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: mysql
            k8s:app.kubernetes.io/name: mysql-router
      toPorts:
        - ports:
            - port: "6446"
