# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - netpols.yaml
  - source.yaml
configMapGenerator:
  - name: values-k8s-gateway
    behavior: create
    files:
      - values.yaml=values.yaml
    literals:
      - env-values.yaml=''
configurations:
  - ../../../utils/helm/kustomizeconfig.yaml
