fullnameOverride: k8s-gateway
# TODO:: Remove phela again after it has been moved to the external gateway
domain: "${SECRET_DOMAIN} phela-intelligence.com"
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    lbipam.cilium.io/ips: "192.168.69.6"
  externalTrafficPolicy: Cluster
watchedResources: ["HTTPRoute", "Service"]
resources:
  requests:
    cpu: 10m
  limits:
    memory: 36Mi
