# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app grafana-system
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  path: ./grafana-system/_base
  components:
    - ../../components/common
  prune: true
  sourceRef:
    kind: ExternalArtifact
    name: infra
    namespace: flux-system
  targetNamespace: grafana-system
  timeout: 15m
  wait: true
