resources:
  - flux-system
  - kube-system
  - monitoring
  - network
  - grafana-system.yaml
  - cert-manager.yaml
  # - piraeus.yaml
  - rabbitmq.yaml
  - spegel.yaml
  - velero.yaml
patches:
  - target:
      kind: Kustomization
    patch: |
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: all
      spec:
        postBuild:
          substituteFrom:
            - name: cluster-secrets
              kind: Secret
        patches:
        - target:
            kind: HelmRelease
          patch: |
            apiVersion: helm.toolkit.fluxcd.io/v2
            kind: HelmRelease
            metadata:
              name: all
            spec:
              interval: 15m
              driftDetection:
                mode: enabled
