# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app piraeus-system
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  path: ./piraeus-datastore/piraeus-operator/_base
  components:
    - ../../../components/common
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: ExternalArtifact
    name: infra
    namespace: flux-system
  targetNamespace: piraeus-datastore
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app piraeus-datastore
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: piraeus-system
      namespace: flux-system
  interval: 1h
  path: ./piraeus-datastore/piraeus-datastore/_base
  components:
    - ../../../components/common
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: ExternalArtifact
    name: infra
    namespace: flux-system
  targetNamespace: piraeus-datastore
  timeout: 5m
  wait: false
