# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-ops-private
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/lingkar/home-ops-private.git
  ref:
    branch: main
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-ops-private
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: home-ops-private
  path: ./base
  prune: true
