# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-credentials
stringData:
  mosquitto.password_file: ENC[AES256_GCM,data:bx8NEc57BobF75mjA4KHx65Hex73ruTXLBo8qoTouTzmCS/9CN2mYD+PVuZpvPaaG+6fF7rAMcUt5gl6aqp8su1dXmYjE6kxSQ9/CiZRyn3/auXReLbXGJzXgxROuwIYF/0aXwzvl7vHqOfPqZtVyOKfTugwkNgY,iv:0MwW07KGYL1Y/amCvBQ/jv3OwhpHQxDJMJsBBOItyyI=,tag:WrDpAp1lLRLAjd7/wqeUYw==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcVY1MjIyTWlCbGJxcitD
        d1FQRjBpb3owOERmbDZxbG9Zc1NmdXd3RjBVCktxMzRhNVhmL0kyclNCM0RNeVZs
        THBobTMvQURPMFE3dUhvYkRSWjVaK0kKLS0tIGlIMGpoaUhHenBHYkVJWlVVUUVm
        NDFhS05ZVU52Y1ZnQWduaGtzWS9vaUEK2htDaWocq+RzMjXIGuLnL+H6cjBdz22M
        N2raR4GuizsaaYRj4xue/BtekeRib3WywJeXFgUet7uK6QOSiJt+dQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T13:30:40Z"
  mac: ENC[AES256_GCM,data:Ecb0cVdzD4UUr1ph5pSqZ7lOYCEXqoZ8tL5MvOyc5VbvgO/c/IMdnKvodXJ1bHyn8Be1B5nu7hcuiT1+HkdFG8SqsOgCTylios7FGXyGUoF8oIHhA0ETRy8kLCmouQlY4eOO1Au0oyPCCyug6jF8X1AeOIg2is2QVHeW/CDWPnw=,iv:SOLVWHWQEVoXKadvCBA0Yu8ApqhoBb1BN9oUC+lXcdY=,tag:1gl1DtdcihpH5rW5reDJEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
