controllers:
  mosquitto:
    initContainers:
      secrets-owner-change:
        image:
          repository: docker.io/busybox
          tag: 1.36.1
        command: ["sh", "-c"]
        args:
          - cp -RL /etc/secret-raw/* /mosquitto/secrets;
            chown -R nobody:nobody /mosquitto/secrets/;
            ls -laL /mosquitto/secrets/;
            ls -laL /etc/secret-raw/;
            find /mosquitto/secrets -type d -exec chmod 700 {} \; ;
            find /mosquitto/secrets -type f -exec chmod 400 {} \; ;
    containers:
      app:
        image:
          repository: docker.io/eclipse-mosquitto
          tag: 2.0.22
        env:
          TZ: Europe/Amsterdam
        # command:
        #   - "/bin/sh"
        #   - "-c"
        #   - "tail -f /dev/null"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 100Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
service:
  app:
    ports:
      mqtt:
        port: 1883
# serviceMonitor:
#   app:
#     endpoints:
#       - port: http
configMaps:
  config:
    data:
      mosquitto.conf: |-
        listener 1883
        password_file /mosquitto/secrets/mosquitto.password_file
persistence:
  mosquitto-credentials-data:
    type: emptyDir
    globalMounts:
      - path: /mosquitto/secrets
  mosquitto-credentials-secret:
    type: secret
    name: mosquitto-credentials
    advancedMounts:
      mosquitto:
        secrets-owner-change:
          - path: /etc/secret-raw/
  config:
    type: configMap
    identifier: config
    globalMounts:
      - path: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
