controllers:
  mosquitto:
    initContainers:
      secret-owner-change:
        name: changeowner
        image: busybox
        command: ["sh", "-c"]
        args:
          - cp -RL /etc/secret-raw/* /mosquitto/secrets;
            chown -R nobody:nobody /mosquitto/secrets/;
            ls -laL /mosquitto/secrets/;
            ls -laL /etc/secret-raw/;
            # find /mosquitto/secrets -type d -exec chmod 700 {} \; ;
            # find /mosquitto/secrets -type f -exec chmod 600 {} \; ;
        volumeMounts:
          - name: mosquitto-credentials-secret
            mountPath: /etc/secret-raw/
    containers:
      app:
        # image:
        #   repository: eclipse-mosquitto
        #   tag: 2.0.22
        image:
          repository: ubuntu
          tag: noble
        env:
          TZ: Europe/Amsterdam
        command:
          - "/bin/sh"
          - "-c"
          - "tail -f /dev/null"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 100Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
service:
  app:
    ports:
      mqtt:
        port: 1883
# serviceMonitor:
#   app:
#     endpoints:
#       - port: http
route:
  app:
    hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
    parentRefs:
      - name: internal
        namespace: network
        sectionName: https
configMaps:
  config:
    data:
      mosquitto.conf: |-
        listener 1883
        password_file /mosquitto/secrets/mosquitto.password_file
persistence:
  mosquitto-credentials-data:
    type: emptyDir
    name: mosquitto-secrets
    defaultMode: 384
    globalMounts:
      - path: /mosquitto/secrets
  mosquitto-credentials-secret:
    type: secret
    name: mosquitto-credentials
  config:
    type: configMap
    identifier: config
    globalMounts:
      - path: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
