# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:s6zCcCqMgp8iavz1D71A+Jf3J94qEEjXc20Omisg2cU416+82wjK4Q==,iv:C7u5inrxkRWPMpQ+mnRwyRltfnjEuSpRrjogUxynhgg=,tag:Uz7QWfnOn+MyOySobK2AdQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZFg2UTJqSFFicmh6Rmlx
        UzcyTFB2alBhYmwyWDZXVk9zbGQwVjVSRWpvCjZoZnNZSlJSZXBRVGlIWFJLMi9q
        eTVrTVA2azZMeTNCSTJsc2t3N04wMVEKLS0tIDR0MWxSSGYrckNyanBZUHRERVZL
        UC9uZ3NmYWtDdFFUNTc4bFg3NlNTakUKxUAwkg2jq+0UyX8bZhF6xIlU8ESEy/cA
        0JWwPjTZhGxFQ7K9eRdrvMq2UqQ+vjcommuz0LhWkN3Ny2zorDkH/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:24:26Z"
  mac: ENC[AES256_GCM,data:6x3WnXDo7GCuSRTD27nuS/b7qbe113Qpixb2W01PVj1KGP3j0Dk2zY9EIIqG9ym0hBRJmsqRRWVtJ8BA68RnZOIUN3Q/nQi5diFLVPVq4Qmjn1vQ+4+g8zMhoqThSpSRsEbQzRvbzKMe1oSScUCy87rcfEUMH3r6+tRFkC4YpoI=,iv:ncpAY8kstDuUnwkxXn5PSicrirl8D6mRBGekFTFXK1Y=,tag:VCFiYnRY8ZSZpzD4/4LYRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
