# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./source.yaml
  - ./secret.sops.yaml
  - ./httproute.yaml
  - ./receiver.yaml
  - ./sops-age.sops.yaml
configMapGenerator:
  - name: values-flux-instance
    behavior: create
    files:
      - values.yaml=values.yaml
    literals:
      - env-values.yaml=''
configurations:
  - ../../../../utils/helm/kustomizeconfig.yaml
