# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:xJtMibMyN6plErb/sBz9lwmeoaP95ou/SN2wHW4gT44=,iv:7E6NSm/sW/cMh5TmJeOiO06ZzvnSghSa/6gC28T6gC0=,tag:LYvc/D5ZON8godWHkFAGaA==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqazZyNFhLVmNiZkRpcGdk
        RE1GeFNubHFUR2dDb05oekxEUzFHQ0xaNnowClF2RVh6dmFTdkZPd2d6YnBnVC9O
        ejVYNW1JM3U3RkZ1WXVuT2FkZW04TUkKLS0tIFY2YTFqbytnejBYclBMK0pkbGFl
        MGFBUW1BQVU5UVBLSWNiaDZmdFhseWsKwU2rACbQVmy8k1urWrYQAYF/FtM4Tuvn
        PGifr+PVrAj+6qNq+rYv12wP4XpLRKzlE/xzBBPa6qVFPJpDB/twBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:23:18Z"
  mac: ENC[AES256_GCM,data:UmIplUOwkk//RU01YIllrTi3rcm6VWLub5VMEkTDJ/bdmRmBm/x/1X+G8kMNrfk7Gt6pc+xphqA+YnMCTq8YDwW3gTMjKFtRilDsVIBd0+zei1Gxs9bSvCuSCJ6Z2+FOGoNCAZRoCr3Nwapgjvtoy1GwZ91laK7IYHc3lm9Ju0s=,iv:ym9udDQNLMpFECn4LxnWfhO6bsvmvg7BUuKjpPQnxHk=,tag:h99ReVl2CS6haaxxxeowXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
