# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:pnG6I6pFMsP8LqHOFwUJyw8YYF9W+SQBMegGDAZI6ACFHOGI+/r3H1oaY0J+fYqlOH952HbW40YtDpR4/oz2ZuYMwgoS70eWzhA=,iv:Gg80XJZ83pfT5l46RdeqaJ3wr0cK9HWX8/uRC7MkiVQ=,tag:aZin98H3PNftU+/zQLGNOQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMk1neDYycm1wY0tBY1RS
        RVdGMllzWGNHbFhmWDlFTDhNSC82U0Ixc0JBClBTTkpPYjlpY1FmenB5ajE2aHJ5
        eVpEMHNucTRnSEZTVnYzL1dIQ3hPeG8KLS0tIExrUmFka1BkUkpqdWJ3NjI4NUxO
        cmFyTXBrU1FCSHkwanNNN2pPQjlnTmsK5inDKq3xFmZuNAFkzelVZnT1DZlnLUhJ
        0aNx7HK+bNTWcO6kcJtoSbsJbprsE/GPPyjnxccKXtV1Q05Is2lFyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:24:48Z"
  mac: ENC[AES256_GCM,data:MNshKHhX+QQfSGHCaW3EkESWmg3K8KgwQnvXcywdXUFbTdKUwdHn01TZIrYIVgSOph6I5ZBKwLTM/F6zFRWOn/cDGEVzQ7YnqDA0cZzoGzg7MGvgDg76M+xuz2+hTM4rhKxNHxnGzbpRarV/TIr2AAn52pv9Ra3WprfWR3vC38Q=,iv:pl1sbq8me6xX9jOCmfyqoxe4OjJMotiEPkjL8oOE0ZQ=,tag:IU79Y6980mfE9cpxfqIYWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
