# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: credentials
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:TKmWpIk4B6wCPJxFD+vb44Y39CngX4dERAM=,iv:GWXwmF0XOlgvCYESYPn8auI9QZza6SVuBmkSoHRGJ1s=,tag:SxkuEo5fmbN17euVW3avjg==,type:str]
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:OyJnU+Ldag==,iv:DcaawPmFJ58fgaMlz9dNUQdGAfGzIprGn+OlY/Yu75A=,tag:4qNGPKo1/p8FP3kery8lyg==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbEVFWG1WZzd2REo5N2xN
        K0FMNDZ5VGE1SUJjcDhYZHVlanJJWjlmZFJJCm9laXhBbTk1b2RHNXA4V3BkaU5a
        L1ZPWFhxZURIdDNIbFQ2RjNCZ1prdzAKLS0tIFR2KzVhNG95QW1Ta213YTNCMlRu
        aVFFTnpxeStjV0lBTml1QzVFRVA3L2MKA81Ml5I+cDUYK3U7T/cnu1rvEiopRE3p
        KaCMcztCTnyG4jyLLDqF3rSCuss2LbIk1Tmhtf7Y8MqjiigpVKxwHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:25:02Z"
  mac: ENC[AES256_GCM,data:TSHO5LDkblEbNbbkDJFmM3LL34AoSS5VR5d+Sy4FCUZwHHKSDb4ceORYL/3V7IdehbvhaJMA1RBIWssvuw9CpDoESTSusjxyMleFbr136scefBfEMp4tp2mQY/V0GJOU3n6WJMgbBDz/O94F9BI0XP24LN20jpyvDfJlymua904=,iv:F4qQLDDIIwV3yiLEq88jPDRmM5oSpT/3gbm0PrsaTQQ=,tag:yIJImd89QyXGmhy0Zk0HeA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
