# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:stdJvvrn/D8UVgmvtzseCwrZtZNgClRLPefX0p9DQpZ8g4CyccvaeIbh0OudK07c15dJYIMCrPNyIv7fmBW4D4PhF+37Kmi4mRKKmhTgQhJYdn5RPpDsunoG9j4vNQkguTe02P5jUq5f36FceYCBaFObnkK8vKrd+FGxvBEXYMkeUhaK3bLZMGXXm7ocb9KTFG8DpAhOYn4T+9OVH457U+zDKQzP4rMP33eBNjUIqmVpMEVD,iv:G/gPoVrVtb6Im3CEsNCWkOiyeVbpI4gDWxl/4m/yDE0=,tag:FBnwB5+agU3lYWmlMvg35A==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNlo2eGdHZ3QxaFhPQ0sz
        bk5yM2tPUU4zRGsrYS80a05kRy9iUUNpQ1g4CmlMbHZhdTFTQk1pN0p3UWRBQ3Nu
        TGNUZ2lOSTEwOWQyOE9JMGI1UGpDYmMKLS0tIDVnWnRHcGNTd3BlcTR2MHVjR1hG
        ZlVUWHJURHhZR3QrSnlZZUQwZks4MzgKzLHDCWzjSorIr1YbAXkOBxIeE5n9KB/T
        rbG3QjUUQPI+4Esgu5w2PjJehFv2ILpFlFuS5A0fwCBUzFSl+y7KuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:22:07Z"
  mac: ENC[AES256_GCM,data:pCmCfsOssygEZb2g1ovXBQWFivAK02AIfsoLpvBryvldW+lWEp3KelLBdc/c5e+lhDIVHLdMeGt5yvl8vkSxiUgMHMqo8IOaZPDYWEwa2KVLh+gnHyMe/+LIwe/ztMNrBx+oVDw/FMIMeybFOBb/BjAHriDZzx//XZrILXuP3DA=,iv:JaEKjntdW/AnBpHy5W1dtwQRMOQyHXxLAuDPq412FH8=,tag:y+ikUCKwheAc+bGwMwNjmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
