# originRequest:
#   originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://cilium-gateway-external.network.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - hostname: "phela-intelligence.com"
    service: *svc
  - hostname: "*.phela-intelligence.com"
    service: *svc
  - service: http_status:404
