# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UPvVvBkovlRRp8QTFyQ=,iv:k282M6vpXDBoSiuPlFPEt1X39i4wSOwyErjF3AffGgg=,tag:khfjMs5/Kzul9SuVCaX42A==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOWc4OUVrTkVPSjBTT3FU
        OU5ML2lPUllHcVE1czNjenVYY095aXQrVFhjCmN5NkFuekY5cTMyWnduc1pFblJo
        OFhrS2lZVzI4NEREZVJ2eDlLUk5pOGcKLS0tIHVzRnJQYmRUMFUreTVDMEFISXk2
        SEVSK0h0R0xVYUxVdlFPeGxJOHNpcHMKa/mEQRX6yapGOYIXg4HvKnEN8RS9eO8E
        4GGVUu7TkXoqsS92CKYY/JwG4VMIAqIr8WQ/GCYX8m66ZNlPULUTtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:25:30Z"
  mac: ENC[AES256_GCM,data:iBVlsbXyCpssMvEM4bkEClfjo4gNdocS0Zu6N+riY1f/aDlDeZRkJGzhgo0KHIC2UUBAJfKdIDapWWC94kNFzGnils8/RgYG2LdtIFnPn/VBhudP/npv/xzJc3CQDUsTQVRPdkg1BEYGgjYxDVKmBYeBgkf0O6edorLR7jFBBsg=,iv:+Cz5OWW9ObPgrEL2fREDHHAbv/Ucm7jfBJndt+Cc+eg=,tag:WkHHpodVlAtVFCYgNhnIpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
