apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rrNHkds8wKA1Yu3ReQ==,iv:vPWeGugc9fYyggNCoe6rhtP7MEJn0LxjgDLhXTh1lCA=,tag:X3JbYZv0bhj26m1IpuNUaQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOWc4OUVrTkVPSjBTT3FU
        OU5ML2lPUllHcVE1czNjenVYY095aXQrVFhjCmN5NkFuekY5cTMyWnduc1pFblJo
        OFhrS2lZVzI4NEREZVJ2eDlLUk5pOGcKLS0tIHVzRnJQYmRUMFUreTVDMEFISXk2
        SEVSK0h0R0xVYUxVdlFPeGxJOHNpcHMKa/mEQRX6yapGOYIXg4HvKnEN8RS9eO8E
        4GGVUu7TkXoqsS92CKYY/JwG4VMIAqIr8WQ/GCYX8m66ZNlPULUTtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T19:42:19Z"
  mac: ENC[AES256_GCM,data:RYA8J68zgHa3rD0PxTJVz+lH4kQVSUC6zPsenHApqIAVUkHb8AfZ10qcqOj8YZuvuBMQfiP1L/a7XutC2lSB9Yr0jndkVD8fRVDgISlc/BDNCGJ+GJWvJTc6FbA7iLykqUmuYGkGzv/qvyUXnTtm5i4c982cGnGS0DbRC3v44oY=,iv:i/vpuGXYPDmtxxje0/3diDok7xxTcRg8jP5xriC4qHo=,tag:+1NAP23UymfDL2kUkInLMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
