apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: mysql
spec:
  credentials:
    source: MySQLConnectionSecret
    connectionSecretRef:
      name: db-conn
  # tls one of preferred(default), skip-verify, true, or custom
  tls: preferred
