# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crossplane.yaml
  - db-conn.sops.yaml
  - innodbcluster.yaml
  - mysql-credentials.sops.yaml
  - netpol.yaml
