# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
stringData:
  rootHost: ENC[AES256_GCM,data:wQ==,iv:UqOxED3s4pD/US96Voy5cPHBVhd8Bdq4iCQo0MXUse4=,tag:tAqZpZPFDHwbSNeBzW0BqA==,type:str]
  rootUser: ENC[AES256_GCM,data:dYDpsA==,iv:MiETBIwnuR4hbvv6OqT1YvyXXEWj+O+cTCv3BMCHLg0=,tag:qzjc1dAhOaiI1QskB+LHpw==,type:str]
  rootPassword: ENC[AES256_GCM,data:OdratNXUhqZKKHSXNrP8ZFU6zotrUJjLc96NVOBhy1t3xONy//+uuJuFv4tHow==,iv:7YjndB9NNTO0TKN2vtn9v33Bs4Rn8s3CMXk+B3tO7a4=,tag:LN2Z86thgDV/eP/dvnVl7w==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobjJyZHJkYmJtUFZLQTJw
        VU91WlZyRW1ZdHMyaGVKOWtJM29POFR5LzFBCksrZnRGbGRjTXIzMkZ1VHN5WnBy
        NzlPaVI0L0V4N2xLOXlOdGdCQzdaY3MKLS0tIHJNeFdRZnJwQzFhOWxaaVBTdTY1
        RDVxek5Jb1NHdGwxTVdVWE5oS2RTblUKMyaa1BBLjSU55b4OMn65dMHeBW8Hgxmx
        yd99eVk8OmEFAb+HUhJ/GQ6650BI1pqG84PMwNkL6oFPYIPCADa9qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T14:33:13Z"
  mac: ENC[AES256_GCM,data:K5ea095IAZDJE1WI0PM8JlpnCnv0vgF09d+mdR3C7G4OymlIdpflcT6xbr/kVh4d8SrakOhwxm1bYoM16jlc/8RsQgJb6TBFcXFeLoL+MiNLYRKu2pW+tgf8a9iBqDDAaVY/AOc1bIcLEiqMVypwVQohmJTj16n+FurIdXKNDHs=,iv:zYWB7E2T35nFjkes63atnUrZgmrcGlHWbBWtSfv3CuM=,tag:pMRrXq4BiXH7ZRCiVjl62A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
