# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mysql
spec:
  description: "Allow the ingress traffic from applicaton namespaces"
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: mysql-router
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: phela
            k8s:app.kubernetes.io/name: phela
      toPorts:
        - ports:
            - port: "6446"
