# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mysql
spec:
  description: "Allow the ingress traffic from applicaton namespaces"
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: mysql-router
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: phela
            k8s:app.kubernetes.io/name: phela
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: crossplane-system
            k8s:pkg.crossplane.io/provider: crossplane-contrib-provider-sql
      toPorts:
        - ports:
            - port: "6446" # MySQL Router primary (RW) classic protocol
            - port: "6447" # MySQL Router read-only classic protocol
            - port: "6450" # MySQL Router read/write split
