# yaml-language-server: $schema=https://json.schemastore.org/kustomization
resources:
  - grafana-dashboard.yaml
  - helmrelease.yaml
  - s3-credentials.sops.yaml
  - source.yaml
configMapGenerator:
  - name: values-velero
    behavior: create
    files:
      - values.yaml=values.yaml
    literals:
      - env-values.yaml=''
configurations:
  - ../../../utils/helm/kustomizeconfig.yaml
