# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: velero-repo-credentials
stringData:
  repository-password: ENC[AES256_GCM,data:JYjaPGsEs9d1g1BNtKxG1jkB29MFWqd1ySdYw6Z1q3zgTsM7aCmPQVK/g1+/NA==,iv:9O5VZfWFEyPhvgcjSdiGbql8ZapWMte6PqT7pyNyGGs=,tag:G5VXZnoZBug8uNSM4GKZGg==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTFFXc1VrbHk5ak5IZ0RR
        S3JIWFZydGZ4SkFjcW0xR1E4SmhwL1pEMXlzCmhjSlFwU1J5RmJWUkorMGxHOWJK
        Q3hPS1UzRTk2OFEwZkVIWXRVTWk4OXMKLS0tIHQrRlpESWNUL1lGalA0OE1pL0dv
        a25PK01Ic1hUVWhOSXRhZEFoLzBEVWMKE9pELgOHVrj6nGKw6jEYqm+l5OcXVBPj
        l+ZOKTYC6dUtA8GhpGEtNPs56fT+VosPPo/U8wvkmJpwrNlDHktx9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:24:17Z"
  mac: ENC[AES256_GCM,data:VOoHc1fDRpuTLE27DPKPEjFvXELA7/MzkpDKHQ66DRKWnVsOrzdhDtFIb0mt3yPG+aH9FkmJTOmYrq91tyqP98uikkoQJZ+g6mKtvAJ+jy15NgRi8O55egGUst8W1kxmfDgJwdXnII1fvtaJ+nsGi8sEK3Fp4SX28sK7XTsK8LA=,iv:pnJsxPtltNzjcOYGu9YLCkZ0Ik4TTTiyi3HKR3bgQa4=,tag:nozciIr0DvECzz1DJPdnfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
