# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  cloud: ENC[AES256_GCM,data:w/q4mIyMMY659YFuJ3Skwl3ZGxLIJFFIG1CcI42/0L5UtBjcyub5WTAqiD4D/0v65WE17USzX3trh0FTrty/4Xns1OP9r3xJ0Oq1xPdmTjpEPtEXL0Gz1BAeCK/yKp07ajPP4GcpulMH8r6AFQWBYA==,iv:iHlXgFNpS/ge0DlRtgQIKQo3jrzCdT/N4TD6FS8L1QA=,tag:awWZytD394kYTdY845ys1A==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQkdHZ0c0ZFZYYmc0c2Vl
        ZkdZYTN0bE1RNHZRRXNEbm5GN2p0cnJHWWpnCnVPdG5ncjd2MWI2REh4NTZMMjdR
        M2ZjNS9GNm1FbWVoMUNYUWZoendaWU0KLS0tIGZFWENDT3J6RGZvYmcvZXNWdEZ2
        SFVzSFl2L1M4VzNDZXYvWU9CVDJGOWMKjgNVjVTYkKaqHFbwi0iV7zTIB2Aba9Gd
        gIi8mXHJvLIB9Uyugy2CPqPkiDIXKN3wHozyq4BuvCR7H3eGuWCwlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T16:26:03Z"
  mac: ENC[AES256_GCM,data:hfbDajKnpDWX+LcG0plwYIMU9XB0UBCPPe40/zV9Jwcr8Zx2pK6kz9AaUJHatzDKFH5HTHByZqnff0iyJaoaLNMLHZ548TS+5kuo3h9jGkAiQN7PkdTh1C/XFfWFUwfbyPCy6L+V3GlTzkM/TLZ+ggowt50YTbNuJvSL7xx9cdI=,iv:VoghchGGF/WItGZRz5OLplrE8X3MQiI+8rQepNOfyOc=,tag:O+lpWs49frvNbsFCwIo+0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
