# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
data:
  cloud: ENC[AES256_GCM,data:CvWbaphjZd19byivJFt1tDvX9pa1SRd6FHOomGg7IVj6kI8nVrmyCvvizV8RRkNamWzHcprrqfmJGq+HUfN3KSd5Jr0hNEHwWTiwu3HuWptaZKSJ6PbkHQZyB5YOKcYo+Hf8w2lqLAGacUmBt7AIRA==,iv:Abx7OtmlVcEO0ND5xEmQD5fTqbpjtlsWsB3gRAquMzM=,tag:/v4dN9dUwBXHGBgs8Y5WFg==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQkdHZ0c0ZFZYYmc0c2Vl
        ZkdZYTN0bE1RNHZRRXNEbm5GN2p0cnJHWWpnCnVPdG5ncjd2MWI2REh4NTZMMjdR
        M2ZjNS9GNm1FbWVoMUNYUWZoendaWU0KLS0tIGZFWENDT3J6RGZvYmcvZXNWdEZ2
        SFVzSFl2L1M4VzNDZXYvWU9CVDJGOWMKjgNVjVTYkKaqHFbwi0iV7zTIB2Aba9Gd
        gIi8mXHJvLIB9Uyugy2CPqPkiDIXKN3wHozyq4BuvCR7H3eGuWCwlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T16:07:59Z"
  mac: ENC[AES256_GCM,data:ypYUKnY9PwC6gP3EwDJ5/01QtFTmXXCJsmexv+MFnDTdMP89oWj2UQnJUYyl1horEnrRA4r3sN3LoP7Os6oyUPM98FdwoFRAntgQdg2rjz0MJRd4jwdOHPjdqDXfzr7tBe7QIcaeHOMyS415EU+O0nyjKMVP1bAVzSCiyEIKaf8=,iv:mb8Hv1Ks8clTWqJ2CIwaKJk8fqQLVJXk9LTsR8qTC9w=,tag:VquR24yNwZ0nzyLUPr78jQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
