# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  cloud: ENC[AES256_GCM,data:w/q4mIyMMY659YFuJ3Skwl3ZGxLIJFFIG1CcI42/0L5UtBjcyub5WTAqiD4D/0v65WE17USzX3trh0FTrty/4Xns1OP9r3xJ0Oq1xPdmTjpEPtEXL0Gz1BAeCK/yKp07ajPP4GcpulMH8r6AFQWBYA==,iv:iHlXgFNpS/ge0DlRtgQIKQo3jrzCdT/N4TD6FS8L1QA=,tag:awWZytD394kYTdY845ys1A==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQkdHZ0c0ZFZYYmc0c2Vl
        ZkdZYTN0bE1RNHZRRXNEbm5GN2p0cnJHWWpnCnVPdG5ncjd2MWI2REh4NTZMMjdR
        M2ZjNS9GNm1FbWVoMUNYUWZoendaWU0KLS0tIGZFWENDT3J6RGZvYmcvZXNWdEZ2
        SFVzSFl2L1M4VzNDZXYvWU9CVDJGOWMKjgNVjVTYkKaqHFbwi0iV7zTIB2Aba9Gd
        gIi8mXHJvLIB9Uyugy2CPqPkiDIXKN3wHozyq4BuvCR7H3eGuWCwlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:24:34Z"
  mac: ENC[AES256_GCM,data:Rz7vizBrvI8mvspFiMzlLvg5H2xBMsACO0jr7u+qYNyRL6cWouyPF7+ZDL61Qfgwo2SbuBKwS4NRHDvMVIpZ6wMSx7zmIOOLeN/hOmswCaWCbbvejsvxUKpiekOKSs+P6E1nPISWuq7k9fEX3EiKM96OezZTuu+BRfVpLP3smOI=,iv:KADI0nE2ZJ8z0sPFnXLoLz+F+6VBqx25/3E2nKlJbnE=,tag:RiacyB5fFUYzN+NjFRhzPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
